version: '3.7'

services:
  ui:
    image: docker.pkg.github.com/RuellePaul/portfolio/portfolio_ui:${VERSION}
    build:
      args:
        - ENVIRONMENT=${ENVIRONMENT}
    volumes:
      - '/node_modules'
    ports:
      - '3000:3000'
    networks:
      - super_network
    logging:
      driver: 'json-file'
      options:
        max-size: 10m
        max-file: "2"

  dispatcher:
    image: docker.pkg.github.com/RuellePaul/portfolio/portfolio_dispatcher:${VERSION}
    build:
      context: ../dispatcher
    volumes:
      - '/etc/letsencrypt:/etc/letsencrypt'
    ports:
      - '80:80'
      - '443:443'
    networks:
      - super_network
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    logging:
      driver: 'json-file'
      options:
        max-size: 10m
        max-file: "2"


networks:
  super_network:
    driver: bridge
